{"error": {"message": "[Errno 22] Invalid argument", "stack_trace": "\nFile -> C:\\Users\\gblai\\Documents\\github\\MEDomicsLab\\flask_server\\utils\\GoExecutionScript.py \nLine -> 77\nFunc.Name -> start\nMessage -> results = self._custom_process(self._json_params)\n\nFile -> C:\\Users\\gblai\\Documents\\github\\MEDomicsLab\\flask_server\\learning\\scripts\\run_experiment.py \nLine -> 54\nFunc.Name -> _custom_process\nMessage -> self.current_experiment.start()\n\nFile -> C:\\Users\\gblai\\Documents\\github\\MEDomicsLab\\flask_server\\learning\\MEDml\\MEDexperiment.py \nLine -> 205\nFunc.Name -> start\nMessage -> self.execute_next_nodes(\n\nFile -> C:\\Users\\gblai\\Documents\\github\\MEDomicsLab\\flask_server\\learning\\MEDml\\MEDexperiment.py \nLine -> 262\nFunc.Name -> execute_next_nodes\nMessage -> 'data': node.execute(experiment, **prev_node.get_info_for_next_node()),\n\nFile -> C:\\Users\\gblai\\Documents\\github\\MEDomicsLab\\flask_server\\learning\\MEDml\\nodes\\NodeObj.py \nLine -> 135\nFunc.Name -> execute\nMessage -> return self._execute(experiment, **kwargs)\n\nFile -> C:\\Users\\gblai\\Documents\\github\\MEDomicsLab\\flask_server\\learning\\MEDml\\nodes\\ModelHandler.py \nLine -> 47\nFunc.Name -> _execute\nMessage -> models = experiment['pycaret_exp'].compare_models(**settings)\n\nFile -> C:\\Users\\gblai\\anaconda3\\envs\\med\\lib\\site-packages\\pycaret\\classification\\oop.py \nLine -> 1180\nFunc.Name -> compare_models\nMessage -> return_values = super().compare_models(\n\nFile -> C:\\Users\\gblai\\anaconda3\\envs\\med\\lib\\site-packages\\pycaret\\internal\\pycaret_experiment\\supervised_experiment.py \nLine -> 890\nFunc.Name -> compare_models\nMessage -> display.move_progress()\n\nFile -> C:\\Users\\gblai\\anaconda3\\envs\\med\\lib\\site-packages\\pycaret\\internal\\display\\display.py \nLine -> 28\nFunc.Name -> move_progress\nMessage -> self._progress_bar_display.step(value)\n\nFile -> C:\\Users\\gblai\\anaconda3\\envs\\med\\lib\\site-packages\\pycaret\\internal\\display\\progress_bar.py \nLine -> 154\nFunc.Name -> step\nMessage -> self.pbar_backend.step(value)\n\nFile -> C:\\Users\\gblai\\anaconda3\\envs\\med\\lib\\site-packages\\pycaret\\internal\\display\\progress_bar.py \nLine -> 37\nFunc.Name -> step\nMessage -> self._pbar.update(value)\n\nFile -> C:\\Users\\gblai\\anaconda3\\envs\\med\\lib\\site-packages\\tqdm\\std.py \nLine -> 1256\nFunc.Name -> update\nMessage -> self.refresh(lock_args=self.lock_args)\n\nFile -> C:\\Users\\gblai\\anaconda3\\envs\\med\\lib\\site-packages\\tqdm\\std.py \nLine -> 1361\nFunc.Name -> refresh\nMessage -> self.display()\n\nFile -> C:\\Users\\gblai\\anaconda3\\envs\\med\\lib\\site-packages\\tqdm\\std.py \nLine -> 1509\nFunc.Name -> display\nMessage -> self.sp(self.__str__() if msg is None else msg)\n\nFile -> C:\\Users\\gblai\\anaconda3\\envs\\med\\lib\\site-packages\\tqdm\\std.py \nLine -> 350\nFunc.Name -> print_status\nMessage -> fp_write('\\r' + s + (' ' * max(last_len[0] - len_s, 0)))\n\nFile -> C:\\Users\\gblai\\anaconda3\\envs\\med\\lib\\site-packages\\tqdm\\std.py \nLine -> 343\nFunc.Name -> fp_write\nMessage -> fp.write(_unicode(s))\n\nFile -> C:\\Users\\gblai\\anaconda3\\envs\\med\\lib\\site-packages\\tqdm\\utils.py \nLine -> 145\nFunc.Name -> inner\nMessage -> return func(*args, **kwargs)\n", "value": "[Errno 22] Invalid argument"}}